### ISSUE TITLE
Components are too tightly coupled

### ISSUE THREAD

**Issue by jessemcculloch** [Microsoft/MRDesignLabs_Unity#1]
I love what you guys are doing, but it seems like your components are all too tightly coupled together, at least for the way that I typically build an app.

I generally build an initialization scene which holds all my objects that are common in most, if not all scenes, such as my Main Camera, my managers (input, spatial, keyword, etc) and any other items that I don't want to have to duplicate in all my scenes.  I would love to use something like the Bounding Box that you guys have, but I can't split up the different pieces across my scenes and still get it to compile.

I tried adding the AppBar and BoundingBox prefabs to my initialization scene, since they would get created upon application launch and persisted across all scenes because of a DoNotDestroy on their parent.  However, when I changed scenes and tried adding a BoundingBoxTarget to my object that I wanted targeted, I get errors that says i'm missing the AppBar and BoundingBox in my scene, which is true at design time, but not at runtime, however I can't compile past that error.

Perhaps the pattern I am using for my Apps is unusual, I'm not sure.  But as of right now, unless I want to duplicate these objects all over my project (which I would rather not), a lot of these components are not usable to me.

**Comment by paseb** [comment]
Hi Jesse,

You are correct in that what is committed as an example isn't the best from an extensible standpoint.  I was out for a couple weeks and didn't get a chance to look over all the examples.  There are generally 2 routes you can go down that I can quickly refactor the example for

1.  Have a singleton that is the ManipulationManager and maintains reference to the shared BoundingBox and AppBar that get spawned from the prefabs.  This would allow for it to exist across scenes but would also mean that you wouldn't get custom bounding boxes for different objects if that's what you wanted.

2. Creating a ManipulationObject class that on start spawns and assigns a bounding box and an app bar for that object.  This would allow just attaching a component to get all the manipulation goodness without requiring another manager.

There are a couple other issues that should be addressed in the bounding box code specifically where using FindObjectByType is being used.  I'll work with the others to address those as well.

I'm going to go down the route of #1 since it's the path of least resistance and provides a bit more functionality from a manager standpoint though as a set of examples either pattern should be supported.

thanks,
-pat

**Comment by paseb** [comment]
Please sync to the latest changes with the Manipulation Manager added for controlling the bounding box and app bar across scenes.  I will look more into getting a "standalone" bounding box and manipulation object so that it can just be coupled with a prefab if you want.
