### ISSUE TITLE
Building for UWP

### ISSUE THREAD

**Issue by quinkennedy** [Microsoft/MRDesignLabs_Unity#32]
When I try to build for UWP, I get a KeyNotFoundException.

```
KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.String].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
MetroCSharpVisualStudioSolutionCreator.WriteSolutionFile (System.String solutionFileName, UnityEditor.Scripting.ScriptCompilation.ScriptAssembly[] csharpAssemblies) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:166)
MetroCSharpVisualStudioSolutionCreator.CreateSolutionFileFrom () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:716)
PostProcessWSA.CreateVisualStudioSolution () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWSA.cs:320)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:221)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:142)
UnityEditor.WSA.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:149)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

I'm hoping to test these examples on an MR headset.
![mrdl settings](https://user-images.githubusercontent.com/1174430/28484480-727aa576-6e27-11e7-8167-dfbaccecd10b.png)

Unity 2017.2.0b4
Windows 10 16241.rs_prerelease.170708-1800

**Comment by quinkennedy** [comment]
I did set the Scripting Backend to .NET

![dot NET scripting backend](https://user-images.githubusercontent.com/1174430/28486760-b8df0df0-6e3a-11e7-9994-169aef38136f.png)

It looks like I don't have the right SDK, but the link from https://developer.microsoft.com/en-us/windows/mixed-reality/install_the_tools doesn't provide me with an SDK that matches my OS build
![SDKs Unity sees](https://user-images.githubusercontent.com/1174430/28486794-170a0024-6e3b-11e7-9463-17ed20769746.png)

![The SDK available for download](https://user-images.githubusercontent.com/1174430/28486759-b8decda4-6e3a-11e7-8dc5-3e34eec72b54.png)

**Comment by paseb** [comment]
Hi Quinn, Looks like there are a number of known issues with the current beta version that might be blocking you.  

- Windows: [WSA] Error messages appear while/after building a project with "Unity C# projects", if the Editor folder contains a script. (918989)
- Windows: [WSA] Reference rewriter fails in 2017.2 with analytics enabled (927848)
- Windows: [XR][WSA] Including "Unity C# Projects" while building to Universal Windows Platform, causes builds to fail (927925)
- XR: GearVR HMD Touchpad does not currently send input through the new input system.
- XR: Haptics with Vive controller is currently disabled due to issues with correctly playing haptics on the correct controller
- XR: Hololens / UWP / PS4 VR Devices not yet supported with the new input system for VR use.
- XR: New API surface for recent UnityEngine.VR.WSA.Input changes has forthcoming breaking changes to land in another beta soon.

I'll see if I can get you access to the internal preview build or what would be needed to allow for that.

thanks,
-pat

**Comment by joleong** [comment]
Hi, I'm having a similar error when trying to build for UWP. I'm using the assets in the HoloWorld tutorial here https://developer.microsoft.com/en-us/windows/mixed-reality/mixed_reality_250

I've followed the settings, Scripting Backend to .NET. My windows 10 build is the Home Insider Preview 16232.rs_prerelease.170624-1334 and SDK Is 16232. So my SDK does seem to match my Windows preview version. 

I'm using Unity 2017.2.0b4

The full error message is:

KeyNotFoundException: The given key was not present in the dictionary.
System.Collections.Generic.Dictionary`2[System.String,System.String].get_Item (System.String key) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:150)
MetroCSharpVisualStudioSolutionCreator.WriteSolutionFile (System.String solutionFileName, UnityEditor.Scripting.ScriptCompilation.ScriptAssembly[] csharpAssemblies) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:166)
MetroCSharpVisualStudioSolutionCreator.CreateSolutionFileFrom () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/MetroCSharpVisualStudioSolutionCreator.cs:716)
PostProcessWSA.CreateVisualStudioSolution () (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/PostProcessWSA.cs:320)
PostProcessWinRT.Process () (at C:/buildslave/unity/build/PlatformDependent/WinRT/SharedSources/CSharp/PostProcessWinRT.cs:221)
UnityEditor.WSA.BuildPostprocessor.DoPostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:142)
UnityEditor.WSA.BuildPostprocessor.PostProcess (BuildPostProcessArgs args) (at C:/buildslave/unity/build/PlatformDependent/MetroPlayer/Extensions/Managed/ExtensionModule.cs:149)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by joleong** [comment]
I'm also planning on building for MR headsets, not Hololens. The HP MR headset I ordered just shipped, so I should get it in a couple of days.  I'm hoping to get this figured out so that I can build test apps for it.

**Comment by thePostFuturist** [comment]
Same issue.

**Comment by paseb** [comment]
@joleong and @thePostFuturist, I'll be doing a build to track down the issue but it could be related to some of the known issues in the b4 beta:

- Windows: [WSA] Error messages appear while/after building a project with "Unity C# projects", if the Editor folder contains a script. (918989)
- Windows: [WSA] Reference rewriter fails in 2017.2 with analytics enabled (927848)
- Windows: [XR][WSA] Including "Unity C# Projects" while building to Universal Windows Platform, causes builds to fail (927925)

Should have more information soon.

thanks,
-pat

**Comment by joleong** [comment]
@paseb Thanks. I just received my HP MR headset today. I was able to get it set up and running with the MR Portal, however when I try testing by Playing in Unity, I'm seeing only a spatial wiremesh in the headset and the game window in Unity shows the image moving around and controlled by the headset. Is there any additional documentation anywhere that covers the headset setup? I also tried making a build with just a cube in the scene with the VR settings in Unity enabled. The build was successful, however, when I try to deploy it from VS 2017 Community (local machine), I'm getting only a white background showing in the MR Portal and just a spatial mesh in the headset. Is there any additional documentation anywhere that details how to get content onto the MR headset? Another question I have is if it is possible to view what the headset is seeing in the MR Portal. I looked for settings but I don't see any. It seems to be either headset mode or simulator mode.

**Comment by paseb** [comment]
Hi everyone,

So here's the primary issues:

1. HTK labeled Dev_Unity_2017.2  is not actually for the beta version of 2017 but for Unity 5.6 MRTP 9
2. MRDL Windows Mixed Reality branch is also targeted for Unity 5.6 MRTP 9

There are a number of input API changes that need to be resolved between the different versions to get them to work and there are also the issues I mentioned above.  As an interim to support MR development on the beta I might create another branch specifically targeted towards supporting the current 2017.2b4 unity beta.  I'll see what I can get working.

@joleong, There should be a setting to set the headset display visual quality to "High" so that you can preview it.  You can then click the little play icon at the bottom of the MRP to get the headset mirror.

thanks,
-pat

**Comment by joleong** [comment]
@paseb Thanks. How can I get hold of Unity 5.6 MRTP 9? According to the documentation, it says that we can only get it from a Microsoft Account Manager.

**Comment by paseb** [comment]
This should all be resolved using the Unity2017.2-Dev branch.
