### ISSUE TITLE
Bounding box not correctly and App Bar too big?

### ISSUE THREAD

**Issue by JoveCat** [Microsoft/MRDesignLabs_Unity#38]
![demo](https://user-images.githubusercontent.com/13938274/29130961-e17b5d40-7d5d-11e7-84a9-2b411d4285db.jpg)

Hello everyone !
I have a object (building) and I am trying to manipulate the translation and rotation. When the App Bar and Bounding box are shown,  the Bounding box is not correctly and App Bar is too big.  Any suggestion on how to fix this.

**Comment by Railboy** [comment]
Hi JoveCat - I assume you mean that the bounding box doesn't match the apparent bounds of the object?

We recently added a new bounds detection mode - by default it's set to _RendererBounds_, which works on all types of Renderers, but _MeshFilter_ Bounds will work better with meshes:

![mfbounds](https://user-images.githubusercontent.com/9789716/29133180-815add80-7ce7-11e7-985f-490be27dd002.PNG)

The scale of the App Bar is constant so if you're using a small model then it will appear to be oversized. You can manually scale the App Bar prefab, which is located in _Assets/MRDesignLab/HUX/Prefabs/Dialogs_, but this isn't recommended because it can make the buttons difficult to read & manipulate in MR. Scaling up your models is preferred, when possible.

**Comment by JoveCat** [comment]
Hi Railboy,  the App Bar scale problem solved. but the bounding box problem remain. even I change to MeshFilterBounds .
Maybe something wrong with my model. I wrap the original model(building) with an empty object. and add Box Collider on it (Mesh Collider not work), and I found when Flattening mode is "Flatten auto","Flatten X" or "do note Flatten", I  can't click the App Bar when playing. only in "Flatten Y" and "Flatten Z", I can click the App Bar. 
when I select "Flatten Y", the bounding box is like this:
![y](https://user-images.githubusercontent.com/13938274/29152696-3d9f278e-7dbb-11e7-8752-2488c0f9ae90.jpg)
and "Flatten Z":
![z](https://user-images.githubusercontent.com/13938274/29152704-4a962b4a-7dbb-11e7-9584-392f6af165a3.jpg)

Any suggestion on how to fix this.

**Comment by Railboy** [comment]
Are you able to send us the mesh so I can investigate?

> I found when Flattening mode is "Flatten auto","Flatten X" or "do note Flatten", I can't click the App Bar when playing. only in "Flatten Y" and "Flatten Z", I can click the App Bar.

I suspect this is due to the App Bar intersecting with either the model's collider or (due to the custom App Bar position) the Bounding Box's drag collider. In that case fine-tuning the App Bar's position should help. But without seeing the scene it's hard to be sure.

**Comment by JoveCat** [comment]
Thanks Railboy, I expect the update to fix it:)

**Comment by Railboy** [comment]
This has turned out to be a very interesting edge case.

The main problem is that this model has a baked-in y rotation offset of ~ 50 degrees.

The bounding box assumes you want it to be aligned with the object's rotation. But here when the building is facing 'forward' it's actually rotated by 50 degrees so you get an unintuitive result.

The orientation can be fixed by parenting the object under a transform to offset its rotation, but that's only half the problem. The rotation baked into the mesh is still there, which gives us a 'fat' bounding box.

(The grey dots represent the mesh bounds for each submesh)
![meshbounds](https://user-images.githubusercontent.com/9789716/29283641-72cbef40-80dc-11e7-89da-ae80dd106a67.PNG)

![meshboundsrotated](https://user-images.githubusercontent.com/9789716/29283662-82d6f880-80dc-11e7-8054-7ac02800bb89.PNG)

We think it's reasonable to expect a bounding box to conform more closely to a mesh like this so we're going to try a 'point sampling' mode where we sample a subset of vertices instead of using the mesh bounds.

Until that's ready you can work around the issue by removing the mesh rotation offset:

![meshoffsetremoved](https://user-images.githubusercontent.com/9789716/29283896-6b3ec558-80dd-11e7-8fa0-48e9ccc3ac13.PNG)

**Comment by JoveCat** [comment]
Thank you, Railboy, sure enough, this is the model problem.
I create an empty GameObject and parenting the object under it. add a box collider on GameObject. so if it possible to put the bounding box according the parent Box Collider, not the object mesh itself?

And how to removing the mesh baked-in rotation offset?  do I need to edit it in a 3D editor?

**Comment by Railboy** [comment]
> add a box collider on GameObject. so if it possible to put the bounding box according to parent Box Collider, not the object mesh itself?

Collider-based bounds are a good idea.

I'm going to re-open this in case other people have suggestions for bounds-detection methods.

**Comment by JoveCat** [comment]
Hi Railboy, I tried to fix the baked-in y rotation offset, and set rotation to 0,0,0.  the bounding box no longer 'fat', but very 'thin'. I had send you new model by email. 
![new](https://user-images.githubusercontent.com/13938274/29327828-12d1c90a-8223-11e7-9725-08a38502f325.jpg)

**Comment by Railboy** [comment]
This is likely related to a bug introduced by the initial prefab state, [described here](https://github.com/Microsoft/MRDesignLabs_Unity/issues/44). A fix has been uploaded.
