### ISSUE TITLE
Bounding Box Target Drag does not correctly correlate to physical movement

### ISSUE THREAD

**Issue by Danta1st** [Microsoft/MRDesignLabs_Unity#5]
Adjusting a Bounding Box Target through the Drag method does not correctly translate the target, and correlate to physical movement.

Moving an object more than a few handfull of cm's is virtually impossible. 

Most notable situations are when Dragging an object and physically rotating.

Reproducable steps:
1. Create and deploy a build with the _ManipulationGizmo_Examples_ scene
2. Drag the left-most target to another location within your environment at least 90 degrees to your side.

**Comment by Railboy** [comment]
Hi Danta1st - could you elaborate a bit on drag not correctly translating the target? Just want to make sure I understand your expected vs. observed behavior.

**Comment by cre8ivepark** [comment]
I am not sure if this is related but, I experienced a situation where the physical hand movement is translated in opposite (or unexpected) direction when I moved the object to certain location. I think repro step was similar to Danta1st's description. When you move any object to your left side (as least 90 degrees) then the translation of hand movement is showing different behavior. Not clear if this is bug of this control level or HoloLens shell since I have experienced similar thing on the shell with Holograms.

**Comment by Railboy** [comment]
Thanks, I'll mark it as a bug for now and follow up after some testing.

**Comment by Danta1st** [comment]
I would expect the behaviour to be equal to, or better than, the behaviour we see in the official Holograms application.

I believe the error has something to do with the usage of the position returned from the _GestureRecognizer.ManipulationUpdatedEvent_ within the _BoundineBoxManipulate_ module.

**Comment by cre8ivepark** [comment]
@Danta1st Do you think this PR is related?
[https://github.com/Microsoft/MRDesignLabs_Unity/pull/8](https://github.com/Microsoft/MRDesignLabs_Unity/pull/8)

**Comment by Danta1st** [comment]
I just reviewed the code, and it seems quite likely. 
I will need to test it out, in order to confirm or deny.

**Comment by Railboy** [comment]
PR #8 has been merged.

**Comment by Railboy** [comment]
Closing this for now - feel free to re-open if you feel these changes don't address your concern.
