### ISSUE TITLE
MRTK and Designlabs_tools duplicated in repo

### ISSUE THREAD

**Issue by DDReaper** [Microsoft/MRDesignLabs_Unity#62]
Is there a reason why there are two copies of both the MRTK and DesignLabs folders / submodules within the repo. 
This seems way too overkill

For that matter, why is the Tools a Submodule and the MRTK copied in the project?

**Comment by paseb** [comment]
Hi @DDReaper, 

The tools as a submodule is for easy inclusion and updating within other projects.  MRTK ideally would also be a submodule rather than a full repo so that you have it properly include in other git repositories.  

Having to pull and copy what is essentially makes it messy to continually upgrade across multiple projects.  With the MRDL tools as a submodule you can simple create a new git repo for your project and submodule the tools to match to the version of Unity you're using.  The purpose is for extensible inclusion in projects as opposed to manual sync and coping into a project.

We also use the tools across multiple examples and need an easy way to keep them up to date by pulling from the original repository.  That said we will be migrating a lot of functionality to MRTK at the dust settles with Unity 2017.2 getting out of beta. 

thanks,
-pat

**Comment by DDReaper** [comment]
Ok, fair enough.
But If I pull the full project in to a repo, they will be duplicated.  Better to have Examples with just the examples.  The DL with the submodules needed to be shared.

Agree though, not much of a concern atm but will be very confusing for new users.

**Comment by paseb** [comment]
Yeah, I can understand and that is why we've add all the notes on the front page about getting the updated submodule in new projects.  The intention was to have a base project with just the tools and MRTK in it as a baseline for developers as opposed to overloading one project with all the examples as well.  We're open to reconsidering if it's felt that everyone would want the examples in the base project as well.  

Within tools there are also a set of lightweight examples as well with the more complete examples in the examples project.  As I mentioned I'll be migrating a lot of the functionality to MRTK as a lot of it really is fundamental UI/UX controls.

thanks,
-pat

**Comment by DDReaper** [comment]
Sounds like a plan. Shout if you need any help with that. Just trying to pitch in with the MRTK-Unity atm

**Comment by paseb** [comment]
Yep, saw the thread on the MVP list and agree with getting more fundamental UI/UX support.  We're also focusing on easy functionality discoverability across inputs and classes.  Would love to know your thoughts on the functionality within MRDL and areas that are lacking.  We're currently working on updating the documentation with the integration into MRTK as well.  

thanks,
-pat

**Comment by DDReaper** [comment]
Looking at the content in the DL, it looks fantastic.  Just need to dig in to seeing how it can be more reusable. Breaking up the individual reusable bits based on what I've seen (in about 30 mins so far :D )
A lot of fantastic stuff to build from.
